version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  republish:
    lang: golang-http
    handler: ./republish
    image: theaxer/nats-republish:latest
    environment:
      target_subject: faas-resp
      nats_url: nats://nats.openfaas:4222
    annotations:
      topic: "faas-req"

  connector-test:
    lang: golang-http
    handler: ./connector-test
    image: theaxer/connector-test:latest
    environment:
      faas_request_subject: faas-req
      target_subject: faas-resp
      nats_url: nats://nats.openfaas:4222
      faas_msg: "Hello world"

